import {
  Swords, Compass, Plane, PawPrint, Gamepad2, CircleDot, Sword,
  Sparkles, Bike, Blocks, LayoutGrid, Sailboat, Brain, Building2,
  Car, Layers, Smile, Cat, MousePointerClick, ChefHat, Pencil,
  GraduationCap, Wheat, Hand, Heart, Flag, Search, Zap, Hash,
  Ghost, Clock, Globe, Grid3x3, Calculator, Users, Skull, Map,
  ArrowUpFromDot, Puzzle, HelpCircle, Bot, Shield, Box, Crosshair,
  Settings, Waves, Rocket, Trophy, EyeOff, BrainCircuit, Tent,
  Timer, Lightbulb, TrendingUp, Type,
  type LucideIcon,
} from 'lucide-react'

export const categoryIcons: Record<string, LucideIcon> = {
  action: Swords,
  adventure: Compass,
  'air-combat': Plane,
  animal: PawPrint,
  arcade: Gamepad2,
  ball: CircleDot,
  basketball: CircleDot,
  battle: Sword,
  'beauty-dress-up': Sparkles,
  bike: Bike,
  block: Blocks,
  board: LayoutGrid,
  boat: Sailboat,
  brain: Brain,
  building: Building2,
  car: Car,
  card: Layers,
  casual: Smile,
  cats: Cat,
  clicker: MousePointerClick,
  cooking: ChefHat,
  drawing: Pencil,
  educational: GraduationCap,
  farming: Wheat,
  fighting: Hand,
  flying: Plane,
  'games-for-girls': Heart,
  golf: Flag,
  'hidden-object': Search,
  'hyper-casual': Zap,
  '2048': Hash,
  horror: Ghost,
  idle: Clock,
  io: Globe,
  'match-3': Grid3x3,
  math: Calculator,
  memory: Brain,
  mmorpg: Users,
  monster: Skull,
  'open-world': Map,
  platformer: ArrowUpFromDot,
  puzzle: Puzzle,
  quiz: HelpCircle,
  racing: Flag,
  robots: Bot,
  rpg: Shield,
  runner: Zap,
  sandbox: Box,
  shooter: Crosshair,
  simulation: Settings,
  snake: Waves,
  space: Rocket,
  sports: Trophy,
  stealth: EyeOff,
  strategy: BrainCircuit,
  survival: Tent,
  tank: Shield,
  'time-management': Timer,
  trivia: Lightbulb,
  tycoon: TrendingUp,
  word: Type,
  zombie: Skull,
}
